version: '2'

services:

  counter1:
    build: axon-demo-counter/
    image: sparcs/counter
    container_name: counter1
    depends_on:
      - rabbitmq
    ports:
      - "30010:8081"    # Web API
    environment:
      SPRING_PROFILES_ACTIVE: ${COUNTER_PROFILES_ACTIVE}
      DISCOVERY_SERVER_HOSTNAME: ${DISCOVERY_SERVER_HOSTNAME}
      SHOP_ID: "000001"

  kiosk1_1:
    build: axon-demo-kiosk/
    image: sparcs/kiosk
    container_name: kiosk1_1
    depends_on:
      - rabbitmq
    ports:
      - "30011:8080"    # Web API
    environment:
      SPRING_PROFILES_ACTIVE: ${KIOSK_PROFILES_ACTIVE}
      DISCOVERY_SERVER_HOSTNAME: ${DISCOVERY_SERVER_HOSTNAME}
      SHOP_ID: "000001"
      KIOSK_INDEX: "01"

  kiosk1_2:
    image: sparcs/kiosk
    container_name: kiosk1_2
    depends_on:
      - rabbitmq
    ports:
      - "30012:8080"    # Web API
    environment:
      SPRING_PROFILES_ACTIVE: ${KIOSK_PROFILES_ACTIVE}
      DISCOVERY_SERVER_HOSTNAME: ${DISCOVERY_SERVER_HOSTNAME}
      SHOP_ID: "000001"
      KIOSK_INDEX: "02"

  counter2:
    image: sparcs/counter
    container_name: counter2
    depends_on:
      - rabbitmq
    ports:
      - "30020:8081"    # Web API
    environment:
      SPRING_PROFILES_ACTIVE: ${COUNTER_PROFILES_ACTIVE}
      DISCOVERY_SERVER_HOSTNAME: ${DISCOVERY_SERVER_HOSTNAME}
      SHOP_ID: "000002"

  kiosk2_1:
    image: sparcs/kiosk
    container_name: kiosk2_1
    depends_on:
      - rabbitmq
    ports:
      - "30021:8080"    # Web API
    environment:
      SPRING_PROFILES_ACTIVE: ${KIOSK_PROFILES_ACTIVE}
      DISCOVERY_SERVER_HOSTNAME: ${DISCOVERY_SERVER_HOSTNAME}
      SHOP_ID: "000002"
      KIOSK_INDEX: "01"

  rabbitmq:
    image: sparcs/rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management Web UI & API
