version: '2'

services:

  rabbitmq:
    image: sparcs/rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management Web UI & API

  discovery:
    build: axon-demo-discovery/
    image: sparcs/discovery
    container_name: discovery
    ports:
      - "8761:8761"    # Web API

  product1:
    build: axon-demo-product/
    image: sparcs/product
    container_name: product1
    depends_on:
      - discovery
    ports:
      - "20011:8082"    # Web API
    environment:
      SPRING_PROFILES_ACTIVE: ${PRODUCT_PROFILES_ACTIVE}
      INSTANCE_ID: "01"

  product2:
    image: sparcs/product
    container_name: product2
    depends_on:
      - discovery
    ports:
      - "20012:8082"    # Web API
    environment:
      SPRING_PROFILES_ACTIVE: ${PRODUCT_PROFILES_ACTIVE}
      INSTANCE_ID: "02"

  counter1:
    build: axon-demo-counter/
    image: sparcs/counter
    container_name: counter1
    depends_on:
      - rabbitmq
      - discovery
    ports:
      - "30010:8081"    # Web API
    environment:
      SPRING_PROFILES_ACTIVE: ${COUNTER_PROFILES_ACTIVE}
      SHOP_ID: "000001"

  kiosk1_1:
    build: axon-demo-kiosk/
    image: sparcs/kiosk
    container_name: kiosk1_1
    depends_on:
      - rabbitmq
      - discovery
    ports:
      - "30011:8080"    # Web API
    environment:
      SPRING_PROFILES_ACTIVE: ${KIOSK_PROFILES_ACTIVE}
      SHOP_ID: "000001"
      KIOSK_INDEX: "01"

  kiosk1_2:
    image: sparcs/kiosk
    container_name: kiosk1_2
    depends_on:
      - rabbitmq
      - discovery
    ports:
      - "30012:8080"    # Web API
    environment:
      SPRING_PROFILES_ACTIVE: ${KIOSK_PROFILES_ACTIVE}
      SHOP_ID: "000001"
      KIOSK_INDEX: "02"

  counter2:
    image: sparcs/counter
    container_name: counter2
    depends_on:
      - rabbitmq
      - discovery
    ports:
      - "30020:8081"    # Web API
    environment:
      SPRING_PROFILES_ACTIVE: ${COUNTER_PROFILES_ACTIVE}
      SHOP_ID: "000002"

  kiosk2_1:
    image: sparcs/kiosk
    container_name: kiosk2_1
    depends_on:
      - rabbitmq
      - discovery
    ports:
      - "30021:8080"    # Web API
    environment:
      SPRING_PROFILES_ACTIVE: ${KIOSK_PROFILES_ACTIVE}
      SHOP_ID: "000002"
      KIOSK_INDEX: "01"
