server:
  port: 8081

counter:
  shop:
    id: "000001"
  amqp:
    host-name: rabbitmq
    kiosk-events-in:
      exchange-name: EVT-${counter.shop.id}
      queue-name: EVT-COUNTER-${counter.shop.id}
    kiosk-commands-out:
      exchange-name: CMD-${counter.shop.id}

spring:
  application:
    name: counter
  datasource:
    url: jdbc:h2:mem:db;MODE=Oracle;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    validation-query: SELECT 1;

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: false
    hibernate:
      ddl-auto: create-drop
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others:  true
        trace: false

eureka:
  instance:
    appname: counter
    instance-id: ${counter.shop.id}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery:8761/eureka/
