server:
  port: 8082

spring:
  application:
    name: product

eureka:
  instance:
    appname: product
    instance-id: 1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery:8761/eureka/
